# Generated by Django 4.0.6 on 2022-07-20 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
