# Generated by Django 4.0.6 on 2022-07-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('slug', models.SlugField(unique=True)),
                ('images', models.ImageField(default='profile_default.jpeg', upload_to='static/worship_images/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
