# Generated by Django 4.0.6 on 2022-07-19 09:05

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPortal', '0002_worships_price_worships_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worships',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='INR', max_digits=7, null=True),
        ),
    ]
