# Generated by Django 4.0.6 on 2022-07-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPortal', '0003_alter_worships_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worships',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='worships',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
