# Generated by Django 4.0.6 on 2022-07-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddToCart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(max_length=4),
        ),
    ]
