# Generated by Django 4.0.6 on 2022-07-21 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPortal', '0003_alter_worships_price'),
        ('AddToCart', '0005_remove_cart_item_cartitem_total_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPortal.worships'),
        ),
    ]
