# Generated by Django 4.0.6 on 2022-07-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddToCart', '0007_alter_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
    ]
