# Generated by Django 4.0.6 on 2022-07-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddToCart', '0008_remove_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price_currency',
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
