# Generated by Django 4.0.6 on 2022-07-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddToCart', '0010_cart_total_price_currency_cartitem_price_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price_currency',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
