# Generated by Django 4.0.6 on 2022-07-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPortal', '0004_remove_worships_price_currency_alter_worships_price'),
        ('AddToCart', '0011_remove_cart_total_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPortal.worships'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
