# Generated by Django 4.0.6 on 2022-07-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddToCart', '0012_cart_item_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
