# Generated by Django 4.0.6 on 2022-07-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddToCart', '0014_remove_cart_item_remove_cart_quantity_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='total_items',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
